language: ruby
rvm:
  - 1.9.3

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible

script:
  - make test

after_failure:
  - (cat .kitchen/logs/*.log | grep -v '^I, ')
